export default function Home() {
  return (
    <div className="flex flex-col items-center pt-16">
      <div className="flex flex-col lg:flex-row items-center gap-8 p-8 max-w-6xl w-full">
        <div className="flex flex-col space-y-4 lg:w-1/2 w-full">

          <h1 className="text-5xl font-bold">
            This is the landing page!
          </h1>

          <p className="text-gray-600 text-lg">
            Elevate your online presence with HD headshots generated by our AI.
            Ideal for social profiles, resumes, and professional portfolios.
          </p>
          
        </div>
      </div>
    </div>
  )
}
